# Requires nightly build of rustfmt
unstable_features = true

# The edition of the Rust Style Guide to follow
style_edition = "2021"
# Enforce line endings, though this should be handled by Git
newline_style = "Unix"
# Keep string literals under the `max_width` with a backslash
format_strings = true
# Format code blocks in documentation
format_code_in_doc_comments = true
# Force a consistent style with macro patterns
format_macro_matchers = true
# Force imports to be grouped by deepest module per crate
imports_granularity = "Module"
# Group stock, external, and current crate imports together with newline
group_imports = "StdExternalCrate"
# Allow a leading pipe before match arms
# <https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#preserve>
match_arm_leading_pipes = "Preserve"
